### ISSUE TITLE
Framework or static library

### ISSUE THREAD

**Issue by stanislavfeldman** [FutureKit/FutureKit#15]
Can I build it to get framework or static library?

**Comment by mishagray** [comment]
So since this is swift code, it can't be used in a static library.   Swift code requires a framework to work correctly. 

Currently using FutureKit with cocoapods, causes it to create a framework.

I still have an open issue to get Carthage support working, which means I need a Framework target somewhere in a project.   Which is a big TBD, but could happen pretty soon.

**Comment by stanislavfeldman** [comment]
And how do you install it with Cocoapods?
For me it does not work.
I got:
[!] Unable to satisfy the following requirements:
- `FutureKit` required by `Podfile`

**Comment by mishagray** [comment]
ping me at michael@futurekit.org if you are still having issues.  (It's probably a bad Podfile).
