### ISSUE TITLE
Question: Cancellation of promises

### ISSUE THREAD

**Issue by o15a3d4l11s2** [FutureKit/FutureKit#43]
I could not find any information on how to cancel a chain of promises manually.
Could you please help me with this?

**Comment by ivanyorgov** [comment]
+1

**Comment by mishagray** [comment]
I started writing a response here... and than it got really big, and I realized it should just be a document...

https://github.com/FutureKit/FutureKit/blob/master/Cancellation.MD

**Comment by o15a3d4l11s2** [comment]
Thanks a lot for the document. I have one question though - I have the following case:

```
let token = doAllTasks().getCancelToken()

// At some point I cancel the tasks
token.cancel()
```

The futures are all like this (firstAsyncTask, secontAsyncTask, etc.):
```
func firstAsyncTask() -> Future<Bool> {
    let p = Promise<Bool>()
    p.onRequestCancel() { _ in
        return .Complete(.Cancelled)
    }

    // Some long operation completes
    p.completeWithSuccess(true)

    return p.future
}
```

And the whole chain:
```
func doAllTasks() -> Future<Bool> {
    return firstAsyncTask().onSuccess(block: { (succeeded) -> Future<Bool> in
        return self.secondAsyncTask()
    }).onSuccess(block: { (succeeded) -> Future<Bool> in
        return self.thirdAsyncTask()
    }).onSuccess(block: { (succeeded) -> Future<Bool> in
        return self.fourthAsyncTask()
    }).onCancel(block: {
        print("Cancel block executed")
    })
}
```
Now if I call the cancellation while the first future is still executing, I can successfully cancel all consecutive operations and "Cancel block executed" is printed.

But if I call the cancellation at a moment after the first future is finished, the whole chain is being executed.

If I call `token.cancel([.ForwardCancelRequestEvenIfThereAreOtherFuturesWaiting])`, then the whole chain get canceled also after the first future is finished.

Is there something that I misunderstood from the documentation? I thought that since I am having only a single token and a single chain, that the cancellation will be automatically forwarded, but it is not. It behaves like your description of [Advanced Stuffs - Future 'Chains' vs Future 'Trees'](https://github.com/FutureKit/FutureKit/blob/master/Cancellation.MD#advanced-stuffs---future-chains--vs-future-trees)

**Comment by mishagray** [comment]
hmm..  Actually that should work exactly like i say... but I don't have this test case...

Let me see if I can add this test case, and validate that it's working right.     

The other feature I want to 'add' is to LOG event that can print out during a DEBUG code that actually shows you that a cancellation is being ignored.     It's clearly detecting two tokens on the same future (onComplete/onSuccess adds a token to a future), so we just have to track down where it's created.

I've actually been contemplating making .ForwardCancelRequestEvenIfThereAreOtherFuturesWaiting the default behavior anyways.   Since it seems most people are hitting the "tree" cancellation issue unintentionally.

**Comment by mishagray** [comment]
So with FutureKit 2.0... we have 'inverted' the default cancel() behavior, so now "ForwardCancelRequestEvenIfThereAreOtherFuturesWaiting" is the default behavior.

**Comment by o15a3d4l11s2** [comment]
Thanks a lot for the information. I created a sample project to test the behaviour in FutureKit 2.0 and it works as expected.
